### ISSUE TITLE
SSR compatible

### ISSUE THREAD

**Issue by tksumanth1994** [gruns/ImmortalDB#20]
Hey, thanks for ImmortalDB. It's really awesome. 😃 

Though I'm trying to use this inside a [nuxt.js](https://nuxtjs.org/) project which has SSR built-in. I want to use ImmortalDB with SSR but the `window` keyword use stops it from being SSR friendly. Could you make it ssr-friendly. So that it uses cookies on the server-side and the same current choice of dbs on the client-side.

Making it ssr-friendly would be a great add-on. Thanks! :)

**Comment by gruns** [comment]
Thanks for your Issue!

> So that it uses cookies on the server-side and the same current choice of dbs
> on the client-side.

Beyond failing gracefully if `window` isn't defined, what steps are required to
"support SSR"? Cookies on the server doesn't make sense to me.

**Comment by kevee** [comment]
We're using ImmortalDB in a Gatsby site, and this package causes the build to fail - the Gatsby site will still include ImmortalDB via webpack to the client, but just the presence of an assumed global window object causes builds to fail.

So if all you do is wrap the `window` references in a conditional checking the typeof window, that would work for us.

**Comment by gruns** [comment]
> So if all you do is wrap the window references in a conditional checking the
> typeof window, that would work for us.

Awesome.

I'll do that shortly.

**Comment by gruns** [comment]
Does https://github.com/gruns/ImmortalDB/commit/9179421fff73dc36b1b81e00d14eef8d7315c684 solve the problem for you?

**Comment by gruns** [comment]
> @gruns Yes, thanks!

Wonderful. This fix will ship in the next version of ImmortalDB, v1.0.3.

Thank you for your help and input Krishna and Kevin. Don't hesitate to let me
know if there's anything else I can do for you.
