### ISSUE TITLE
Option to remove all cookies set with ImmortalDB

### ISSUE THREAD

**Issue by Neugierdsnase** [gruns/ImmortalDB#21]
From a quick glance at the code this could relatively easy be implemented via a seperate function (something like `removeAll()`) or as a default behaviour when no `key` argument is provided to the `remove()` method. If you tell me if this is something you want and if so, which way you prefer I would try and write this as a PR myself.

**Comment by Neugierdsnase** [comment]
Hi, thanks for your reply. Yeah, my case might be an edge case, idk, you'll be judge of that:

I'm using ImmortalDB to create a rather elaborate autosaving feature for a game (played in the browser). Rather then periodically saving the whole game (which can be a lot of information), I only save the state of individual game objects (think: buildings, characters) when a meaningful change has occured. The `removeAll()` would be to reset game.

So to abstract the problem: Whenever cookies are set programmatically, where you might not have full control over the amount and (exact) key? I don't know if that ever happens, I thought it would be handy, but I have since solved the problem in another way.

**Comment by Neugierdsnase** [comment]
> I considered ImmortalDB keeping track of all keys that ImmortalDB has written,
but that remains out of band for now.

I see, well, it isn't a pressing issue I suppose and yes, I have since solved the problem by tracking the setting of the cookies in the application itself (which is arguably a more sensible way to go anyway). Thanks for your insights, appreciate it (and the project as a whole). Have a splendid day. Cheers!

**Comment by gruns** [comment]
Great. Thank you for your Issue.

Don't hesitate to let me know if there's anything else I can do for you.
