### ISSUE TITLE
Support for KV Storage

### ISSUE THREAD

**Issue by mikheevm** [gruns/ImmortalDB#26]
I've seen this article about new storage coming:
https://developers.google.com/web/updates/2019/03/kv-storage

Basically this is like localStorage but async and with better performance

It's currently not supported in browsers except Chrome 74+ but I'm curious if this should be supported too (maybe with a polyfill)

**Comment by gruns** [comment]
This would be awesome to add once widely supported. It's brand new, and still
even locked behind an experimental flag.

```
Note: The KV Storage module is currently available in Chrome 74 if you have
the experimental web platform features flag turned on:
(chrome://flags/#enable-experimental-web-platform-features).
```

If and when kv-storage is added and supported in browsers, support in ImmortalDB
would be awesome.

**Comment by gruns** [comment]
From further reading, `kv-storage` is built on top of IndexedDB

  > KV storage is layered on top of IndexedDB, storing its data in a specific
  > database, so the developer can fall back to using IndexedDB directly when
  > necessary.

  * https://www.chromestatus.com/feature/6428344899862528

and thus provides no additional redundancy beyond `IndexedDbStore`.

A separate `kv-storage` implementation could be built and added, but it's
redundant (and wastes space) on top of `IndexedDbStore`.

Closing. Please re-open this issue if you have a specific use case in mind where
you'd want `kvStorageStore` over `IndexedDbStore`.
