### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by tonxxd** [gruns/ImmortalDB#33]
Hello, is it possible to trigger a callback when a key is set?
Thank you in advance

**Comment by gruns** [comment]
`set()` returns a `Promise` that resolves once the key and value have
been set. So, to get a callback once `set()` completes, you can chain
Promises with `.then()`.

```js
const db = ImmortalDB.ImmortalDB

const p = db.set('key', 'value')
p.then(() => {
   alert('callback!')
})
```

Does this suffice for your needs?

**Comment by tonxxd** [comment]
Hi @gruns thanks for the reply.

Actually what I was wondering is if there is the possibility to subscribe to events.
In my use case I have to send a post request each time I set a variable in ImmortalDB. 
So I need something like 
`ImmortalDB.on("set", (key, value) => something )`
which is called each time `ImmortalDB.set(key, value)` is called.

Of course I can just make a wrapper around the function but it would be easier if the feature was already in the library.

Probably just adding a `this.onSet(k, v)` at the end of the `set()` function could solve the issue. Then we can configure it like `ImmortalDB.onSet = (k, v) => {}` before any call.

**Comment by gruns** [comment]
Aha! Thank you for elucidating.

In the spirit of minimal, focused software, I want to understand your
use case more before we add events to ImmortalDB.

1) Is it someone else's code that's calling `ImmortalDB.set()`? That is,
   is it code you don't control? For example, a third party library that
   you can't add `.then()` to.

2) What work are you doing in the `set()` callback? Is this something
   that's better done by ImmortalDB itself?

**Comment by gruns** [comment]
@tonxxd Little bump. Does

```js
db.set(key, value).then(() => something)
```

suffice for your use case?

**Comment by tonxxd** [comment]
Yes it does, thanks

**Comment by gruns** [comment]
Awesome.

Thank you again, Enrico. Don't hesitate to let me know if there's anything else I can do for you.
